<a href="https://colab.research.google.com/github/kisanpawar/KML-SEM2/blob/main/DV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
data = [[1,2,3],[4,5,6],[7,8,9]]

In [3]:
convertArray = np.array(data)
print(convertArray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
print(convertArray[:1])
print(np.sum(convertArray[:1]).flatten()) #flatten again add into array
print(np.prod(convertArray[:3]).flatten()) #flatten again add into array

[[1 2 3]]
[6]
[362880]


In [1]:
import pandas as pd
import numpy as np
series =  pd.Series(np.random.randint(10,100,100))

series = series.abs()

mean =  series.mean()
print(mean)
median_val = series.median()
print(median_val)

std_dev =  series.std()
print(std_dev)

skewness = series.skew()
print(skewness)

top_10 = series.nlargest(10)
print(mean)

cumulative_series = series.cumsum()
print(cumulative_series)

print("Top 10 values:\n", top_10)

54.26
56.0
24.945848422840893
-0.008377490208577674
54.26
0       14
1       36
2       72
3      124
4      183
      ... 
95    5255
96    5288
97    5341
98    5385
99    5426
Length: 100, dtype: int64
Top 10 values:
 57    98
38    96
55    96
64    96
39    95
66    95
75    90
82    90
25    89
80    89
dtype: int64


In [32]:
# Create DataFrame
df = pd.DataFrame(np.random.randint(1, 1001, (1000, 5)), columns=['A',
'B', 'C', 'D', 'E'])
# Add column 'F' as the product of A and B
df['F'] = df['A'] * df['B']
# Compute row-wise statistics
df['Row_Sum'] = df.sum(axis=1)
df['Row_Mean'] = df.mean(axis=1)
df['Row_Variance'] = df.var(axis=1)
# Filter rows where C > 700 and D is even
filtered_df = df[(df['C'] > 700) & (df['D'] % 2 == 0)]
print(filtered_df.head())


      A    B    C    D    E       F  Row_Sum       Row_Mean  Row_Variance
5   927  526  861  850  614  487602   491380  140394.285714  4.874844e+10
6   331  667  997  944  577  220777   224293   64083.714286  1.004365e+10
15  860  292  898  896  849  251120   254915   72832.857143  1.298767e+10
16  810  386  756  856   65  312660   315533   90152.285714  2.006106e+10
18  659  155  769  566   60  102145   104354   29815.428571  2.157430e+09


Empty DataFrame
Columns: [A, B, C, D, E, F, Row_Sum, Row_Mean, Row_Variance]
Index: []


In [40]:
chunk_size = 50000
chunks = pd.read_csv())


In [11]:
#Write a map-reduce program to count the number of occurrences of each alphabetic
#character in the given dataset. The count for each letter should be case-insensitive (i.e., include
#both upper-case and lower-case versions of the letter; Ignore non-alphabetic character
from collections import Counter
import re
def map_function(text):
 # Remove non-alphabetic characters and convert text to lowercase
 cleaned_text = re.sub(r'[^a-zA-Z]', '', text.lower())
 # Return list of characters
 return list(cleaned_text)
def reduce_function(mapped_data):
 # Use Counter to count occurrences of each character
 return dict(Counter(mapped_data))

file_path = r"sample_data/map.txt"
with open(file_path, 'r') as file:
  dataset = file.read()
  mapped_data = map_function(dataset)
  reduced_data = reduce_function(mapped_data)
  print("Character Occurrences:")
  for char, count in reduced_data.items():
    print(f"{char}: {count}")





Character Occurrences:
h: 3
e: 6
l: 5
o: 3
w: 1
r: 2
d: 2
t: 3
i: 2
s: 3
a: 5
m: 2
p: 3
u: 2
c: 2
x: 1
n: 1
b: 1


In [12]:
 #Write a map-reduce program to count the number of occurrences of each word in the given
#dataset. (A word is defined as any string of alphabetic characters appearing between nonalphabetic characters like nature's is two words. The count should be case-insensitive. If a word
#occurs multiple times in a line, all should be counted)

import re


In [ ]:
from functools import reduce
from collections import defaultdict
dataset = [
 "Nature's beauty is unmatched in Nature's own way.",
 "The quick brown fox jumps over the lazy dog.",
 "Hello world! This is a test, hello world."
]
def mapper(line):
 # Use regular expression to split words, considering alphabetic characters only.
 words = re.findall(r'[a-zA-Z]+', line.lower())
 return words